twist_to_ackermann:
  ros__parameters:

    wheel_base: 1.34    #[meter]
    max_steering_angle: 30.0    #[degree]
    max_linear_vel: 7.0   #[meter/second]
    max_angular_vel: 12.0   #[rad/second] = max_linear_vel/tan(max_steering_angle)

motor_controll:
  ros__parameters:

    mid_drive:
      rear_wheel_radius: 0.3302   # 0.6604/2 [meter] 
      speed_ratio: 0.0025
      max_rpm: 9000
      min_rpm: 900
      #enable_inverse: false
      can_message:
        id: 0x030E    #corresponding VESC ID(Extend frame format)
        dlc: 8
        is_rtr: false
        is_extended: true
        is_error: false

    brake_servo:
      can_message:
        id: 0x0D
        dlc: 1
        is_rtr: false
        is_extended: false
        is_error: false

    steering:
      #mid_point_val: 
      convert_constant: 0.000001   #Scale = 1e-6
      can_message:
        id: 0x00C    #corresponding VESC ID
        dlc: 8
        is_rtr: false
        is_extended: true
        is_error: false
        ext_id: 0x30C 