/**:
    ros__parameters:
      video_device: "/dev/video4"
      framerate: 60.0
      io_method: "mmap"
      frame_id: "camera_link"
      pixel_format: "yuyv"
      image_width: 640
      image_height: 480
      camera_name: "brio_camera"
      camera_info_url: "package://evpi_bringup/config/camera_info.yaml"